name: Sync Database

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - working-directory: social-media-be
        run: npm ci

      - working-directory: social-media-be
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run cron
